language: java
sudo: false

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - travis_wait 30 ./mvnw clean install
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
